# Generated by Django 6.0.5 on 2026-06-07 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('base_url', models.URLField(blank=True)),
                ('requires_tenant_provisioning', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provision_endpoint', models.CharField(default='/internal/tenants/provision/', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenantserviceprovision',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tenantserviceprovision',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantserviceprovision',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_provisions', to='tenants.serviceregistry'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantserviceprovision',
            unique_together={('tenant', 'service')},
        ),
        migrations.RemoveField(
            model_name='tenantserviceprovision',
            name='service_name',
        ),
    ]
