# Generated by Django 6.0.5 on 2026-06-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_serviceregistry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantserviceprovision',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_provisions', to='tenants.serviceregistry'),
        ),
    ]
