# Generated by Django 5.1 on 2026-06-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenantserviceprovision_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantserviceprovision',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_provisions', to='tenants.serviceregistry'),
        ),
    ]
