# Generated by Django 5.1 on 2026-07-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenantdomain_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='schema_name',
        ),
        migrations.RemoveField(
            model_name='tenantserviceprovision',
            name='schema_name',
        ),
    ]
